// Compatibility-bundle order. Lazy production entries import their feature
// coordinators directly; this barrel preserves synchronous classic startup.
import './seerr-status';
import './request-manager';
import './api';
import './seerr';
import './modal';
import './item-details';
import './issue-reporter';
import './seamless-scroll';
import './discovery/filter-utils';
import './discovery/base';
import { networkDiscovery } from './discovery/network';
import { personDiscovery } from './discovery/person';
import { genreDiscovery } from './discovery/genre';
import { tagDiscovery } from './discovery/tag';
import { collectionDiscovery } from './discovery/collection';
import './hss-discovery-handler';
import './more-info-modal/styles';
import './more-info-modal/data';
import './more-info-modal/seasons';
import './more-info-modal/badges';
import './more-info-modal/render';
import './more-info-modal/actions-tv';
import './more-info-modal/actions';
import './more-info-modal/init';
import './ui/icons';
import './ui/styles';
import './ui/popover';
import './ui/badges';
import './ui/cards';
import './ui/buttons';
import './ui/quota';
import './ui/results';
import './ui/request-modals';
import './ui/season-modal';

networkDiscovery.start();
personDiscovery.start();
genreDiscovery.start();
tagDiscovery.start();
collectionDiscovery.start();
