// Lazy feature entry for anime-filler-warnings — generated by scripts/new-feature.js.
// Import purity is a loader contract: all browser work begins in activate().
import type { FeatureModule, FeatureScope } from '../core/feature-loader';
import { installAnimeFillerWarnings } from '../enhanced/anime-filler-warnings';

export const animeFillerWarningsFeature: FeatureModule = Object.freeze({
    activate(scope: FeatureScope) {
        if (!scope.isCurrent()) return;
        const dispose = installAnimeFillerWarnings(scope.signal, () => scope.isCurrent());
        if (!scope.isCurrent()) {
            dispose();
            return;
        }
        scope.track(dispose);
    },
});

export const activate: FeatureModule['activate'] = (scope) => animeFillerWarningsFeature.activate(scope);
