using System;
using System.Globalization;
using Microsoft.AspNetCore.Http;

namespace Jellyfin.Plugin.JellyfinCanopy.Platform
{
    /// <summary>
    /// Assigns and carries the correlation id for one Platform v1 request.
    ///
    /// The id is generated by the HOST, never accepted from the caller. A caller-supplied
    /// correlation id would be attacker-controlled text written verbatim into every log
    /// line for the request — log injection, and a way to make two unrelated requests
    /// look like one. The same principle as acting identity (ADR-0011): caller-supplied
    /// values are attribution at best, never authority.
    /// </summary>
    public static class PlatformCorrelation
    {
        /// <summary>The response header carrying the id back to the caller.</summary>
        public const string HeaderName = "X-Correlation-Id";

        /// <summary>Key under which the id is stashed on <see cref="HttpContext.Items"/>.</summary>
        internal const string ItemsKey = "JellyfinCanopy.Platform.CorrelationId";

        /// <summary>
        /// The id for this request, generating and stashing one on first use.
        ///
        /// Stable within a request: the envelope body, the response header and every log
        /// line must all show the same value or the id is worse than useless.
        /// </summary>
        public static string For(HttpContext context)
        {
            ArgumentNullException.ThrowIfNull(context);

            if (context.Items.TryGetValue(ItemsKey, out var existing) && existing is string cached)
            {
                return cached;
            }

            var generated = Generate();
            context.Items[ItemsKey] = generated;
            return generated;
        }

        /// <summary>
        /// A fresh id.
        ///
        /// Format is 32 lowercase hex characters. Deliberately not a raw GUID string with
        /// dashes and not sequential: it must be safe to paste into a log grep, carry no
        /// meaning a consumer could come to depend on, and reveal nothing about request
        /// volume or ordering.
        /// </summary>
        public static string Generate() => Guid.NewGuid().ToString("N", CultureInfo.InvariantCulture);
    }
}
