'use strict';

/**
 * Paved-road feature scaffolder.
 *
 *   node scripts/new-feature.js <kebab-name> [--area <area>] [--dry-run]
 *
 * Generates the four files a new feature starts from, all marked with
 * TODO(<name>) so nothing half-generated slips through review:
 *
 *   Jellyfin.Plugin.JellyfinCanopy/src/<area>/<name>.ts   typed client module
 *   Jellyfin.Plugin.JellyfinCanopy/Controllers/<Pascal>Controller.cs
 *   e2e/<name>.spec.ts                                      Playwright stub
 *   docs/<docs-area>/<name>.md                              docs stub
 *
 * It also appends the module import to the area barrel (src/<area>/index.ts)
 * — the bundle build fails on unreachable src/ modules, so a fresh scaffold
 * must be wired to keep the repo green — and prints the remaining manual
 * steps (SettingDescriptors entry, configPage data-config-key, mkdocs nav).
 *
 * This is a template, not a framework: the barrel append is the only edit it
 * makes to an existing file.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.join(__dirname, '..');
const AREAS = ['enhanced', 'seerr', 'arr', 'tags', 'elsewhere', 'extras', 'others'];
const DOCS_AREA = {
    enhanced: 'enhanced',
    seerr: 'seerr',
    arr: 'arr',
    tags: 'enhanced',
    elsewhere: 'elsewhere',
    extras: 'other',
    others: 'other',
};

function usage(message) {
    if (message) console.error(`new-feature: ${message}\n`);
    console.error('Usage: node scripts/new-feature.js <kebab-name> [--area <area>] [--dry-run]');
    console.error(`  --area     src/ area barrel to target (default: enhanced; one of ${AREAS.join(', ')})`);
    console.error('  --dry-run  print the files that would be created without writing anything');
    process.exit(message ? 2 : 0);
}

function parseArgs(argv) {
    const args = { name: null, area: 'enhanced', dryRun: false };
    for (let i = 0; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === '--dry-run') {
            args.dryRun = true;
        } else if (arg === '--area') {
            args.area = argv[++i];
        } else if (arg === '--help' || arg === '-h') {
            usage();
        } else if (!args.name) {
            args.name = arg;
        } else {
            usage(`unexpected argument "${arg}"`);
        }
    }
    if (!args.name) usage('missing <kebab-name>');
    if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(args.name)) {
        usage(`"${args.name}" is not kebab-case (expected e.g. watch-party)`);
    }
    if (!AREAS.includes(args.area)) usage(`unknown area "${args.area}"`);
    return args;
}

/** watch-party -> WatchParty */
function pascalCase(kebab) {
    return kebab.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join('');
}

/** watch-party -> watchParty */
function camelCase(kebab) {
    const pascal = pascalCase(kebab);
    return pascal[0].toLowerCase() + pascal.slice(1);
}

/** watch-party -> Watch Party */
function titleCase(kebab) {
    return kebab.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join(' ');
}

// ── templates ────────────────────────────────────────────────────────────────

function clientModule(name, area) {
    const pascal = pascalCase(name);
    const camel = camelCase(name);
    const title = titleCase(name);
    return `// src/${area}/${name}.ts
//
// ${title} — TODO(${name}): one-line summary of what this feature does.
//
// Generated by scripts/new-feature.js. The paved road (see CONTRIBUTING.md
// and docs/v12-platform.md):
//   - typed module over JC.core: lifecycle handle + durable ensureInjected
//   - config: JC.pluginConfig (admin defaults) / JC.currentSettings (per-user)
//   - live updates: JC.core.live channels (LIVE.*) instead of polling
//
// Performance rules (docs/advanced/performance-rules.md — grep 'PERF(Rn' for
// the implementation sites; the checklist in CONTRIBUTING.md gates review):
//   R1  Pre-paint or reserved space: ensureInjected {prePaint:true} or
//       min-width/expandIn — never insert-then-move.
//   R2  Decorations on existing content are position:absolute overlays.
//   R3  No own body-wide MutationObserver — JC.core.dom.onBodyMutation or
//       navigation events; never observe attributes body-wide.
//   R4  Cache layout reads per navigation; none inside observer ticks.
//   R5  No setInterval for DOM detection; data polls are page-scoped +
//       visibility-gated + push-nudged (JC.core.live).
//   R6  No remote assets: use assetUrl() from core/asset-urls (example
//       below) — never a CDN URL.
//   R7  Build DOM off-DOM, insert once with content ready; late async data
//       fades in (opacity only).
//   R8  Sync work in a mutation batch stays under ~2ms; overflow to async.
//
// Security rule (docs/advanced/client-security.md — enforced by
// src/test/escape-guard.test.ts):
//   X1  Every \${...} that lands in HTML is a constant/trusted producer, a
//       coerced number (Number(x) || 0), or escapeHtml(...)-wrapped — in
//       attribute AND text positions; toast() renders innerHTML and JC.t()
//       does NOT escape params.

import { JC } from '../globals';
import { register } from '../core/lifecycle';
import { ensureInjected } from '../core/dom-observer';
import { LIVE, on } from '../core/live';
// R6: third-party assets are served from the local asset cache — resolve any
// icon/font/css through assetUrl() instead of hardcoding a remote URL, e.g.:
//   import { assetUrl } from '../core/asset-urls';
//   icon.src = assetUrl('icons/sonarr.svg');

/** Public surface exposed as window.JellyfinCanopy.${camel}. */
export interface ${pascal}Api {
    /** Wire the feature up (idempotent — also runs on config hot-reload). */
    initialize(): void;
    /** Remove injected UI and release tracked resources. */
    teardown(): void;
}

// Frozen-contract registration: adds JC.${camel} to the shared JEGlobal type.
// TODO(${name}): move this into the area's *-surface.d.ts if the surface grows.
declare module '../types/jc' {
    interface JEGlobal {
        /** ${name}: TODO(${name}) one-line description. */
        ${camel}?: ${pascal}Api;
    }
}

const logPrefix = '🪼 Jellyfin Canopy: ${title}:';
const lifecycle = register('${name}');

let injection: { run(): void; remove(): void } | null = null;

/** TODO(${name}): point this at the feature's real admin/user toggle. */
function isEnabled(): boolean {
    return JC.pluginConfig?.${pascal}Enabled === true;
}

/**
 * Build (and attach) the feature's UI under the anchor.
 * TODO(${name}): real markup — use the ui-kit so injected UI wears native
 * MUI markup and theme tokens, e.g.:
 *   const button = JC.core.ui!.muiIconButton({ icon: 'extension', title: JC.t!('${name.replace(/-/g, '_')}_tooltip') });
 */
function build(anchor: HTMLElement): HTMLElement {
    const container = document.createElement('div');
    container.id = 'jc-${name}';
    anchor.appendChild(container);
    return container;
}

function initialize(): void {
    if (!isEnabled()) {
        teardown();
        return;
    }
    if (injection) {
        injection.run();
        return;
    }

    // Durable, idempotent injection: re-attaches across React re-renders,
    // navigations and the /video round trip (docs/v12-platform.md §3).
    // TODO(${name}): pick the real anchor (header tray? page container?) and
    // pass { headerTray: true } for AppBar injections.
    injection = ensureInjected(
        'jc-${name}',
        () => document.querySelector<HTMLElement>('.page:not(.hide)'),
        build
    );

    // React to pushes instead of polling. TODO(${name}): keep only the
    // channels the feature needs (LIVE.CONFIG_CHANGED re-runs initialize so
    // admin toggles apply without a reload).
    lifecycle.track(on(LIVE.CONFIG_CHANGED, () => { initialize(); }));
}

function teardown(): void {
    injection?.remove();
    injection = null;
    lifecycle.teardown();
}

JC.${camel} = { initialize, teardown };

initialize();

console.log(\`\${logPrefix} module loaded\`);
`;
}

function controller(name) {
    const pascal = pascalCase(name);
    const title = titleCase(name);
    return `using System.Net.Http;
using Jellyfin.Plugin.JellyfinCanopy.Services;
using Jellyfin.Plugin.JellyfinCanopy.Services.Seerr;
using MediaBrowser.Controller.Library;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.JellyfinCanopy.Controllers
{
    /// <summary>
    /// ${title} endpoints. TODO(${name}): describe the feature's HTTP surface.
    /// Generated by scripts/new-feature.js.
    /// </summary>
    [Route("JellyfinCanopy")]
    [ApiController]
    public class ${pascal}Controller : JellyfinCanopyControllerBase
    {
        public ${pascal}Controller(
            IHttpClientFactory httpClientFactory,
            ILogger<${pascal}Controller> logger,
            IUserManager userManager,
            ISeerrCache seerrCache,
            IPluginConfigProvider configProvider)
            : base(httpClientFactory, logger, userManager, seerrCache, configProvider)
        {
        }

        /// <summary>
        /// TODO(${name}): replace with the real endpoint(s). Conventions:
        ///  - bare [Authorize] = any authenticated user; admin-only endpoints use
        ///    [Authorize(Policy = Policies.RequiresElevation)] (bare 403, empty body;
        ///    add "using MediaBrowser.Common.Api;") — clients branch on status only.
        ///  - JSON envelopes are for business errors, never authz.
        /// </summary>
        [HttpGet("${name}/status")]
        [Authorize]
        public IActionResult GetStatus()
        {
            var config = _configProvider.ConfigurationOrNull;
            if (config == null)
                return StatusCode(503, new { success = false, message = "Plugin configuration unavailable." });

            // TODO(${name}): read the real toggle, e.g. config.${pascal}Enabled.
            return Ok(new { enabled = true });
        }
    }
}
`;
}

function e2eSpec(name) {
    return `// E2E stub for ${name} — generated by scripts/new-feature.js.
// TODO(${name}): assert the feature's real user-visible behavior, then remove
// the fixme so the spec runs in CI.
import { test, expect, loginAs } from './fixtures/auth';

test.describe('${name}', () => {
    test.fixme(true, 'scaffolded by scripts/new-feature.js — implement');

    test('renders for an enabled user without console errors', async ({ page, consoleErrors }) => {
        await loginAs(page, 'admin', consoleErrors);

        // TODO(${name}): drive the feature and assert what the user sees.
        await expect(page.locator('#jc-${name}')).toBeVisible();

        expect(consoleErrors.real()).toEqual([]);
    });
});
`;
}

function docsStub(name) {
    const title = titleCase(name);
    return `# ${title}

TODO(${name}): document the feature — what it does, its admin settings
(Dashboard -> Plugins -> Jellyfin Canopy) and any per-user settings
(Enhanced panel), with screenshots.

Generated by \`scripts/new-feature.js\`. Add this page to the \`nav:\` section
of \`mkdocs.yml\` and validate with \`mkdocs build --strict\`.
`;
}

function nextSteps(name, area, files, dryRun) {
    const pascal = pascalCase(name);
    return `
${dryRun ? 'Would create (dry run — nothing written):' : 'Created:'}
${files.map((file) => `  ${path.relative(REPO_ROOT, file)}`).join('\n')}

${dryRun ? 'Would append' : 'Appended'} to Jellyfin.Plugin.JellyfinCanopy/src/${area}/index.ts:
  import './${name}';
(the bundle build fails on src/ modules unreachable from main.ts — reposition
the import if execution order within the area matters)

Remaining wire-up TODOs:

1. SettingDescriptors — register the feature's settings (single source of truth)
   in Jellyfin.Plugin.JellyfinCanopy/Configuration/SettingDescriptors.cs
   (BuildRegistry), plus the backing property:

     // TODO(${name}) in PluginConfiguration.cs:
     //   public bool ${pascal}Enabled { get; set; }   (+ default in the ctor)
     // TODO(${name}) in SettingDescriptors.BuildRegistry():
     //   Public("${pascal}Enabled", c => c.${pascal}Enabled),
     //   (use PublicUser(...) + a UserSettings property for per-user overrides)
     // NOTE: the golden payload snapshots in JellyfinCanopy.Tests/Snapshots
     //   pin the config contract — update them via the documented flow.

2. Admin config page — add the control to Configuration/configPage.html with
     data-config-key="${pascal}Enabled"
   (the config-page binder loads/saves every data-config-key automatically).

3. Docs — add docs/${DOCS_AREA[area]}/${name}.md to mkdocs.yml nav; then run
     mkdocs build --strict

4. Implement, then run the gates:
     npm run typecheck:src && npm run lint && npm run test:client && npm run build:bundle
     dotnet build Jellyfin.Plugin.JellyfinCanopy/JellyfinCanopy.csproj -c Release && dotnet test
     npm run e2e   (JF_BASE_URL=... against a seeded server; see e2e/docker/seed.sh)
`;
}

// ── main ─────────────────────────────────────────────────────────────────────

function main() {
    const { name, area, dryRun } = parseArgs(process.argv.slice(2));
    const pascal = pascalCase(name);

    const targets = [
        {
            file: path.join(REPO_ROOT, 'Jellyfin.Plugin.JellyfinCanopy', 'src', area, `${name}.ts`),
            content: clientModule(name, area),
        },
        {
            file: path.join(REPO_ROOT, 'Jellyfin.Plugin.JellyfinCanopy', 'Controllers', `${pascal}Controller.cs`),
            content: controller(name),
        },
        {
            file: path.join(REPO_ROOT, 'e2e', `${name}.spec.ts`),
            content: e2eSpec(name),
        },
        {
            file: path.join(REPO_ROOT, 'docs', DOCS_AREA[area], `${name}.md`),
            content: docsStub(name),
        },
    ];

    const existing = targets.filter((target) => fs.existsSync(target.file));
    if (existing.length > 0) {
        console.error('new-feature: refusing to overwrite existing files:');
        for (const target of existing) console.error(`  ${path.relative(REPO_ROOT, target.file)}`);
        process.exit(1);
    }

    const barrel = path.join(REPO_ROOT, 'Jellyfin.Plugin.JellyfinCanopy', 'src', area, 'index.ts');
    if (!fs.existsSync(barrel)) {
        console.error(`new-feature: area barrel not found: ${path.relative(REPO_ROOT, barrel)}`);
        process.exit(1);
    }

    if (!dryRun) {
        for (const target of targets) {
            fs.mkdirSync(path.dirname(target.file), { recursive: true });
            fs.writeFileSync(target.file, target.content);
        }

        // Wire the module into the area barrel — the bundle build fails on
        // src/ modules unreachable from main.ts, so a fresh scaffold must be
        // imported to keep the repo green.
        const barrelSource = fs.readFileSync(barrel, 'utf8');
        const importLine = `import './${name}';`;
        if (!barrelSource.includes(importLine)) {
            const separator = barrelSource.endsWith('\n') ? '' : '\n';
            fs.appendFileSync(
                barrel,
                `${separator}// TODO(${name}): reposition if execution order within the area matters.\n${importLine}\n`
            );
        }
    }
    console.log(nextSteps(name, area, targets.map((target) => target.file), dryRun));
}

main();
