'use strict';

/**
 * Paved-road feature scaffolder.
 *
 *   node scripts/new-feature.js <kebab-name> [--area <area>] [--dry-run]
 *
 * Generates the five files a new feature starts from, all marked with
 * TODO(<name>) so nothing half-generated slips through review:
 *
 *   Jellyfin.Plugin.JellyfinCanopy/src/<area>/<name>.ts   import-pure implementation
 *   Jellyfin.Plugin.JellyfinCanopy/src/entries/<name>.ts  lazy feature entry
 *   Jellyfin.Plugin.JellyfinCanopy/Controllers/<Pascal>Controller.cs
 *   e2e/<name>.spec.ts                                      Playwright stub
 *   docs/<docs-area>/<name>.md                              docs stub
 *
 * It also wires the lazy entry into ESM_ENTRIES and adds its loader descriptor
 * to the boot-only feature catalog. Both architecture anchors are validated
 * before anything is written, so an architecture change fails closed with
 * explicit manual guidance instead of leaving a half-wired feature behind.
 *
 * This is a template, not a framework: settings, route predicates and the
 * generated TODO behavior still require deliberate implementation.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.join(__dirname, '..');
const AREAS = ['enhanced', 'seerr', 'arr', 'tags', 'elsewhere', 'extras', 'others'];
const DOCS_AREA = {
    enhanced: 'enhanced',
    seerr: 'seerr',
    arr: 'arr',
    tags: 'enhanced',
    elsewhere: 'elsewhere',
    extras: 'other',
    others: 'other',
};

class UsageError extends Error {
    constructor(message, exitCode = 2) {
        super(message);
        this.name = 'UsageError';
        this.exitCode = exitCode;
    }
}

function usageText(message) {
    const prefix = message ? `new-feature: ${message}\n\n` : '';
    return `${prefix}Usage: node scripts/new-feature.js <kebab-name> [--area <area>] [--dry-run]\n`
        + `  --area     src/ implementation area (default: enhanced; one of ${AREAS.join(', ')})\n`
        + '  --dry-run  print files and wiring changes without writing anything\n';
}

function parseArgs(argv) {
    const args = { name: null, area: 'enhanced', dryRun: false };
    for (let i = 0; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === '--dry-run') {
            args.dryRun = true;
        } else if (arg === '--area') {
            args.area = argv[++i];
        } else if (arg === '--help' || arg === '-h') {
            throw new UsageError('', 0);
        } else if (!args.name) {
            args.name = arg;
        } else {
            throw new UsageError(`unexpected argument "${arg}"`);
        }
    }
    if (!args.name) throw new UsageError('missing <kebab-name>');
    if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(args.name)) {
        throw new UsageError(`"${args.name}" is not kebab-case (expected e.g. watch-party)`);
    }
    if (!args.area) throw new UsageError('missing value for --area');
    if (!AREAS.includes(args.area)) throw new UsageError(`unknown area "${args.area}"`);
    return args;
}

/** watch-party -> WatchParty */
function pascalCase(kebab) {
    return kebab.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join('');
}

/** watch-party -> watchParty */
function camelCase(kebab) {
    const pascal = pascalCase(kebab);
    return pascal[0].toLowerCase() + pascal.slice(1);
}

/** watch-party -> Watch Party */
function titleCase(kebab) {
    return kebab.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join(' ');
}

// ── templates ────────────────────────────────────────────────────────────────

function clientModule(name, area) {
    const pascal = pascalCase(name);
    const title = titleCase(name);
    return `// src/${area}/${name}.ts
//
// ${title} — TODO(${name}): one-line summary of what this feature does.
//
// Generated by scripts/new-feature.js. The paved road (see CONTRIBUTING.md
// and docs/developers.md):
//   - importing this module is side-effect free
//   - activation and cleanup are owned by the lazy feature loader scope
//   - config/route eligibility stays in entries/feature-catalog.ts
//
// Performance rules (docs/developers.md#performance-rules — grep 'PERF(Rn' for
// the implementation sites; the checklist in CONTRIBUTING.md gates review):
//   R1  Pre-paint or reserved space: ensureInjected {prePaint:true} or
//       min-width/expandIn — never insert-then-move.
//   R2  Decorations on existing content are position:absolute overlays.
//   R3  No own body-wide MutationObserver — JC.core.dom.onBodyMutation or
//       navigation events; never observe attributes body-wide.
//   R4  Cache layout reads per navigation; none inside observer ticks.
//   R5  No setInterval for DOM detection; data polls are page-scoped +
//       visibility-gated + push-nudged (JC.core.live).
//   R6  No remote assets: use assetUrl() from core/asset-urls (example
//       below) — never a CDN URL.
//   R7  Build DOM off-DOM, insert once with content ready; late async data
//       fades in (opacity only).
//   R8  Sync work in a mutation batch stays under ~2ms; overflow to async.
//
// Security rule (docs/developers.md#client-security — enforced by
// src/test/escape-guard.test.ts):
//   X1  Every \${...} that lands in HTML is a constant/trusted producer, a
//       coerced number (Number(x) || 0), or escapeHtml(...)-wrapped — in
//       attribute AND text positions; toast() renders innerHTML and JC.t()
//       does NOT escape params.

import { ensureInjected } from '../core/dom-observer';
// R6: third-party assets are served from the local asset cache — resolve any
// icon/font/css through assetUrl() instead of hardcoding a remote URL, e.g.:
//   import { assetUrl } from '../core/asset-urls';
//   icon.src = assetUrl('icons/sonarr.svg');

/**
 * Build (and attach) the feature's UI under the anchor.
 * TODO(${name}): real markup — use the ui-kit so injected UI wears native
 * MUI markup and theme tokens, e.g.:
 *   const button = JC.core.ui!.muiIconButton({ icon: 'extension', title: JC.t!('${name.replace(/-/g, '_')}_tooltip') });
 */
function build(anchor: HTMLElement): HTMLElement {
    const container = document.createElement('div');
    container.id = 'jc-${name}';
    anchor.appendChild(container);
    return container;
}

/**
 * Install one loader-owned ${title} activation.
 * Importing this module performs no DOM, listener, timer or network work.
 */
export function install${pascal}(): () => void {
    // Durable, idempotent injection survives React re-renders and navigation.
    // TODO(${name}): select the real anchor and add { headerTray: true } for
    // AppBar injection. Use { prePaint: true } when hiding/moving native UI.
    const injection = ensureInjected(
        'jc-${name}',
        () => document.querySelector<HTMLElement>('.page:not(.hide)'),
        build
    );
    let disposed = false;
    return () => {
        if (disposed) return;
        disposed = true;
        injection.remove();
    };
}
`;
}

function entryModule(name, area) {
    const pascal = pascalCase(name);
    const camel = camelCase(name);
    return `// Lazy feature entry for ${name} — generated by scripts/new-feature.js.
// Import purity is a loader contract: all browser work begins in activate().
import type { FeatureModule, FeatureScope } from '../core/feature-loader';
import { install${pascal} } from '../${area}/${name}';

export const ${camel}Feature: FeatureModule = Object.freeze({
    activate(scope: FeatureScope) {
        if (!scope.isCurrent()) return;
        const dispose = install${pascal}();
        if (!scope.isCurrent()) {
            dispose();
            return;
        }
        scope.track(dispose);
    },
});

export const activate: FeatureModule['activate'] = (scope) => ${camel}Feature.activate(scope);
`;
}

function controller(name) {
    const pascal = pascalCase(name);
    const title = titleCase(name);
    return `using System.Net.Http;
using Jellyfin.Plugin.JellyfinCanopy.Services;
using Jellyfin.Plugin.JellyfinCanopy.Services.Seerr;
using MediaBrowser.Controller.Library;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.JellyfinCanopy.Controllers
{
    /// <summary>
    /// ${title} endpoints. TODO(${name}): describe the feature's HTTP surface.
    /// Generated by scripts/new-feature.js.
    /// </summary>
    [Route("JellyfinCanopy")]
    [ApiController]
    public class ${pascal}Controller : JellyfinCanopyControllerBase
    {
        public ${pascal}Controller(
            IHttpClientFactory httpClientFactory,
            ILogger<${pascal}Controller> logger,
            IUserManager userManager,
            ISeerrCache seerrCache,
            IPluginConfigProvider configProvider)
            : base(httpClientFactory, logger, userManager, seerrCache, configProvider)
        {
        }

        /// <summary>
        /// TODO(${name}): replace with the real endpoint(s). Conventions:
        ///  - bare [Authorize] = any authenticated user; admin-only endpoints use
        ///    [Authorize(Policy = Policies.RequiresElevation)] (bare 403, empty body;
        ///    add "using MediaBrowser.Common.Api;") — clients branch on status only.
        ///  - JSON envelopes are for business errors, never authz.
        /// </summary>
        [HttpGet("${name}/status")]
        [Authorize]
        public IActionResult GetStatus()
        {
            var config = _configProvider.ConfigurationOrNull;
            if (config == null)
                return StatusCode(503, new { success = false, message = "Plugin configuration unavailable." });

            // TODO(${name}): read the real toggle, e.g. config.${pascal}Enabled.
            return Ok(new { enabled = true });
        }
    }
}
`;
}

function e2eSpec(name) {
    return `// E2E stub for ${name} — generated by scripts/new-feature.js.
// TODO(${name}): assert the feature's real user-visible behavior, then remove
// the fixme so the spec runs in CI.
import { test, expect, loginAs } from './fixtures/auth';

test.describe('${name}', () => {
    test.fixme(true, 'scaffolded by scripts/new-feature.js — implement');

    test('renders for an enabled user without console errors', async ({ page, consoleErrors }) => {
        await loginAs(page, 'admin', consoleErrors);

        // TODO(${name}): drive the feature and assert what the user sees.
        await expect(page.locator('#jc-${name}')).toBeVisible();

        expect(consoleErrors.real()).toEqual([]);
    });
});
`;
}

function docsStub(name) {
    const title = titleCase(name);
    return `# ${title}

TODO(${name}): document the feature — what it does, its admin settings
(Dashboard -> Plugins -> Jellyfin Canopy) and any per-user settings
(Enhanced panel), with screenshots.

Generated by \`scripts/new-feature.js\`. Add this page to the \`nav:\` section
of \`mkdocs.yml\` and validate with \`mkdocs build --strict\`.
`;
}

function architectureError(owner, expected, manual) {
    return new Error(
        `cannot wire ${owner}: expected exactly one ${expected}. `
        + 'The post-#318 client architecture may have changed; no files were written.\n'
        + `Wire it manually with:\n${manual}`
    );
}

function wireEsmEntry(source, name) {
    const anchor = 'const ESM_ENTRIES = Object.freeze({';
    if (source.split(anchor).length !== 2) {
        throw architectureError(
            'the client manifest entry',
            `${anchor} anchor in scripts/build-bundle.js`,
            `  '${name}': path.join(SRC_ROOT, 'entries', '${name}.ts'),`
        );
    }
    const existing = new RegExp(`^[ \\t]*(?:'${name}'|${name}):`, 'm');
    if (existing.test(source)) {
        throw new Error(`cannot wire the client manifest entry: ESM_ENTRIES already contains "${name}"; no files were written`);
    }
    const start = source.indexOf(anchor);
    const end = source.indexOf('\n});', start);
    if (end < 0) {
        throw architectureError(
            'the client manifest entry',
            'ESM_ENTRIES closing "});" in scripts/build-bundle.js',
            `  '${name}': path.join(SRC_ROOT, 'entries', '${name}.ts'),`
        );
    }
    const line = `    '${name}': path.join(SRC_ROOT, 'entries', '${name}.ts'),`;
    return `${source.slice(0, end)}\n${line}${source.slice(end)}`;
}

function catalogDescriptor(name) {
    const pascal = pascalCase(name);
    return `    {
        id: '${name}',
        entry: '${name}',
        scope: 'identity',
        restartOnConfigChange: true,
        isEnabled: (state) => Boolean(state.identity)
            && JC.pluginConfig?.${pascal}Enabled === true,
        // TODO(${name}): narrow this predicate (and use navigation scope) when
        // the feature is meaningful only on specific routes.
        isApplicable: () => true,
    },`;
}

function wireFeatureCatalog(source, name) {
    const anchor = 'export const builtInFeatureDescriptors: readonly ClientFeatureDescriptor[] = Object.freeze([';
    if (source.split(anchor).length !== 2) {
        throw architectureError(
            'the feature catalog descriptor',
            `${anchor} anchor in src/entries/feature-catalog.ts`,
            catalogDescriptor(name)
        );
    }
    const existing = new RegExp(`^[ \\t]*id: '${name}',`, 'm');
    if (existing.test(source)) {
        throw new Error(`cannot wire the feature catalog descriptor: "${name}" is already registered; no files were written`);
    }
    const start = source.indexOf(anchor);
    const end = source.indexOf('\n]);', start);
    if (end < 0) {
        throw architectureError(
            'the feature catalog descriptor',
            'builtInFeatureDescriptors closing "]);" in src/entries/feature-catalog.ts',
            catalogDescriptor(name)
        );
    }
    return `${source.slice(0, end)}\n${catalogDescriptor(name)}${source.slice(end)}`;
}

function prepareArchitectureWiring(repoRoot, name) {
    const buildFile = path.join(repoRoot, 'scripts', 'build-bundle.js');
    const catalogFile = path.join(
        repoRoot,
        'Jellyfin.Plugin.JellyfinCanopy',
        'src',
        'entries',
        'feature-catalog.ts'
    );
    for (const file of [buildFile, catalogFile]) {
        if (!fs.existsSync(file)) {
            throw architectureError(
                path.relative(repoRoot, file),
                'post-#318 architecture file',
                `  create the lazy entry, add it to ESM_ENTRIES, and register its descriptor in feature-catalog.ts`
            );
        }
    }
    return [
        { file: buildFile, content: wireEsmEntry(fs.readFileSync(buildFile, 'utf8'), name) },
        { file: catalogFile, content: wireFeatureCatalog(fs.readFileSync(catalogFile, 'utf8'), name) },
    ];
}

function nextSteps(repoRoot, name, area, files, dryRun) {
    const pascal = pascalCase(name);
    return `
${dryRun ? 'Would create (dry run — nothing written):' : 'Created:'}
${files.map((file) => `  ${path.relative(repoRoot, file)}`).join('\n')}

${dryRun ? 'Would wire' : 'Wired'} lazy client activation through:
  scripts/build-bundle.js (ESM_ENTRIES['${name}'])
  Jellyfin.Plugin.JellyfinCanopy/src/entries/feature-catalog.ts (descriptor '${name}')

The generated descriptor defaults to identity scope and an always-applicable
route predicate. Narrow isApplicable (and use navigation scope) when this UI is
route-specific. Do not import the implementation from boot or an area barrel.

Remaining wire-up TODOs:

1. SettingDescriptors — register the feature's settings (single source of truth)
   in Jellyfin.Plugin.JellyfinCanopy/Configuration/SettingDescriptors.cs
   (BuildRegistry), plus the backing property:

     // TODO(${name}) in PluginConfiguration.cs:
     //   public bool ${pascal}Enabled { get; set; }   (+ default in the ctor)
     // TODO(${name}) in SettingDescriptors.BuildRegistry():
     //   Public("${pascal}Enabled", c => c.${pascal}Enabled),
     //   (use PublicUser(...) + a UserSettings property for per-user overrides)
     // NOTE: the golden payload snapshots in JellyfinCanopy.Tests/Snapshots
     //   pin the config contract — update them via the documented flow.

2. Admin config page — add the control to Configuration/configPage.html with
     data-config-key="${pascal}Enabled"
   (the config-page binder loads/saves every data-config-key automatically).

3. Docs — add docs/${DOCS_AREA[area]}/${name}.md to mkdocs.yml nav; then run
     mkdocs build --strict

4. Bundle budgets — build the implemented feature, measure its static and
   expanded closures, then deliberately adjust scripts/bundle-budgets.json if
   the new entry/output counts or byte totals exceed the current reviewed caps.

5. Implement, then run the gates:
     ./verify.sh lint   # findings/cap are advisory; keep this on its own line
     npm run typecheck:src && npm run test:client && npm run build:bundle
     dotnet build Jellyfin.Plugin.JellyfinCanopy/JellyfinCanopy.csproj -c Release && dotnet test
     npm run e2e   (JF_BASE_URL=... against a seeded server; see e2e/docker/seed.sh)
`;
}

// ── main ─────────────────────────────────────────────────────────────────────

function scaffoldFeature({ name, area, dryRun }, options = {}) {
    const repoRoot = options.repoRoot || REPO_ROOT;
    const pascal = pascalCase(name);

    const targets = [
        {
            file: path.join(repoRoot, 'Jellyfin.Plugin.JellyfinCanopy', 'src', area, `${name}.ts`),
            content: clientModule(name, area),
        },
        {
            file: path.join(repoRoot, 'Jellyfin.Plugin.JellyfinCanopy', 'src', 'entries', `${name}.ts`),
            content: entryModule(name, area),
        },
        {
            file: path.join(repoRoot, 'Jellyfin.Plugin.JellyfinCanopy', 'Controllers', `${pascal}Controller.cs`),
            content: controller(name),
        },
        {
            file: path.join(repoRoot, 'e2e', `${name}.spec.ts`),
            content: e2eSpec(name),
        },
        {
            file: path.join(repoRoot, 'docs', DOCS_AREA[area], `${name}.md`),
            content: docsStub(name),
        },
    ];

    const existing = targets.filter((target) => fs.existsSync(target.file));
    if (existing.length > 0) {
        const files = existing.map((target) => `  ${path.relative(repoRoot, target.file)}`).join('\n');
        throw new Error(`refusing to overwrite existing files; no files were written:\n${files}`);
    }

    // Validate and render both #318 wiring edits before creating anything.
    const architectureWrites = prepareArchitectureWiring(repoRoot, name);

    if (!dryRun) {
        for (const target of targets) {
            fs.mkdirSync(path.dirname(target.file), { recursive: true });
            fs.writeFileSync(target.file, target.content);
        }
        for (const write of architectureWrites) fs.writeFileSync(write.file, write.content);
    }
    return nextSteps(repoRoot, name, area, targets.map((target) => target.file), dryRun);
}

function main(argv = process.argv.slice(2), io = console, options = {}) {
    try {
        const args = parseArgs(argv);
        io.log(scaffoldFeature(args, options));
        return 0;
    } catch (error) {
        if (error instanceof UsageError) {
            io.error(usageText(error.message));
            return error.exitCode;
        }
        io.error(`new-feature: ${error instanceof Error ? error.message : String(error)}`);
        return 1;
    }
}

if (require.main === module) process.exitCode = main();

module.exports = {
    clientModule,
    entryModule,
    main,
    parseArgs,
    scaffoldFeature,
    wireEsmEntry,
    wireFeatureCatalog,
};
